[workspace]
members = [".", "shell"]


[package]
name = "fluss"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
winit = { version = "0.29" }
flo_binding = "2"
shell = { path = "shell" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
time = "0.3.20"

[profile.release]
opt-level = 3
lto = true
strip = true
