[package]
name = "trist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter-highlight = "0.20"
tree-sitter-rust = "0.20"
tree-sitter-javascript = "0.20"
