[package]
name = "fluss"
version = "0.1.0"
edition = "2021"

[dependencies]
flo_draw = { path = "../flo_draw/draw", default-features = false, features = ["render-opengl"] }
futures = "0.3"
image = "0.24"
smallvec = "1.11"
rusttype = "0.9"
